'''
Created on 10 Nov 2013
@author: Alex
'''

import os

ALLUSERSPROFILE = os.environ.get("ALLUSERSPROFILE", None)
APPDATA = os.environ.get("APPDATA", None)
ASLLOG = os.environ.get("ASL.LOG", None)
COMMONPROGRAMFILES = os.environ.get("COMMONPROGRAMFILES", None)
COMMONPROGRAMFILESx86 = os.environ.get("COMMONPROGRAMFILES(X86)", None)
COMMONPROGRAMW6432 = os.environ.get("COMMONPROGRAMW6432", None)
COMPUTERNAME = os.environ.get("COMPUTERNAME", None)
COMSPEC = os.environ.get("COMSPEC", None)
CONFIGSETROOT = os.environ.get("CONFIGSETROOT", None)
DJANGO_SETTINGS_MODULE = os.environ.get("DJANGO_SETTINGS_MODULE", None)
FP_NO_HOST_CHECK = os.environ.get("FP_NO_HOST_CHECK", None)
HOMEDRIVE = os.environ.get("HOMEDRIVE", None)
HOMEPATH = os.environ.get("HOMEPATH", None)
LOCALAPPDATA = os.environ.get("LOCALAPPDATA", None)
LOGONSERVER = os.environ.get("LOGONSERVER", None)
NUMBER_OF_PROCESSORS = os.environ.get("NUMBER_OF_PROCESSORS", None)
OS = os.environ.get("OS", None)
PATH = os.environ.get("PATH", None)
PATHEXT = os.environ.get("PATHEXT", None)
PROCESSOR_ARCHITECTURE = os.environ.get("PROCESSOR_ARCHITECTURE", None)
PROCESSOR_IDENTIFIER = os.environ.get("PROCESSOR_IDENTIFIER", None)
PROCESSOR_LEVEL = os.environ.get("PROCESSOR_LEVEL", None)
PROCESSOR_REVISION = os.environ.get("PROCESSOR_REVISION", None)
PROGRAMDATA = os.environ.get("PROGRAMDATA", None)
PROGRAMFILES = os.environ.get("PROGRAMFILES", None)
PROGRAMFILESx86 = os.environ.get("PROGRAMFILES(X86)", None)
PROGRAMW6432 = os.environ.get("PROGRAMW6432", None)
PROMPT = os.environ.get("PROMPT", None)
PSMODULEPATH = os.environ.get("PSMODULEPATH", None)
PUBLIC = os.environ.get("PUBLIC", None)
PYDEV_COMPLETER_PYTHONPATH = os.environ.get("PYDEV_COMPLETER_PYTHONPATH", None)
PYDEV_CONSOLE_ENCODING = os.environ.get("PYDEV_CONSOLE_ENCODING", None)
PYTHONIOENCODING = os.environ.get("PYTHONIOENCODING", None)
PYTHONPATH = os.environ.get("PYTHONPATH", None)
SESSIONNAME = os.environ.get("SESSIONNAME", None)
SSH_AGENT_PID = os.environ.get("SSH_AGENT_PID", None)
SSH_AUTH_SOCK = os.environ.get("SSH_AUTH_SOCK", None)
SYSTEMDRIVE = os.environ.get("SYSTEMDRIVE", None)
SYSTEMROOT = os.environ.get("SYSTEMROOT", None)
TEMP = os.environ.get("TEMP", None)
TMP = os.environ.get("TMP", None)
USERDOMAIN = os.environ.get("USERDOMAIN", None)
USERDOMAIN_ROAMINGPROFILE = os.environ.get("USERDOMAIN_ROAMINGPROFILE", None)
USERNAME = os.environ.get("USERNAME", None)
USERPROFILE = os.environ.get("USERPROFILE", None)
WINDIR = os.environ.get("WINDIR", None)
